TRUNCATE TABLE accounts CASCADE;
TRUNCATE TABLE sessions CASCADE;
TRUNCATE TABLE verifications CASCADE;
TRUNCATE TABLE users CASCADE;
TRUNCATE TABLE topics CASCADE;
TRUNCATE TABLE "topic_anchors" CASCADE;
TRUNCATE TABLE games CASCADE;
TRUNCATE TABLE "games_players" CASCADE;